### ISSUE TITLE
Support for slash commands

### ISSUE THREAD

**Issue by dhzdhd** [Manipal-OSF/OSF-bot#4]
discord.py as of now, does not support slash commands.

We can switch to [this discord wrapper](https://github.com/iDevision/enhanced-discord.py
) which is a fork of discord.py that supports slash commands.

**Comment by dhzdhd** [comment]
Valid alternatives are
1) https://github.com/goverfl0w/discord-interactions
2) https://pypi.org/project/disnake/
3) https://pypi.org/project/discord-py-slash-command/

Although, I am not sure about how stable these repos will be.

**Comment by Shubhaankar-Sharma** [comment]
Lets just use the third one so that we can switch to the most popular fork of discord.py in the future easily

**Comment by dhzdhd** [comment]
Alright

**Comment by dhzdhd** [comment]
Having talked to some experienced discord devs the past month, it seems that disnake is the way to go
Easy integration with discord.py and gives us access to the latest API features.

https://pypi.org/project/disnake/
